### ISSUE TITLE
AutoTrack filter

### ISSUE THREAD

**Issue by benbatya** [de-code/layered-vision#56]
This is the tracking issue for the autotrack feature originally mentioned at [python-tf-bodypix#67](https://github.com/de-code/python-tf-bodypix/issues/67)
Make AutoTrack a filter that can be applied.
This will require a new filter type which takes the bodypix masks as an argument to the filter function

**Comment by de-code** [comment]
Great, thank you.

> This will require a new filter type which takes the bodypix masks as an argument to the filter function

Currently the filters just receive a single input. That works fine with just using the a single mask. But in this case you probably want to have multiple inputs. Also the current approach when blurring the background is to pass the webcam image into two *branches*, whereas the background branch is blurred and the foreground branch has the applied to it. "Zooming" both probably requires a filter after both branches are applied, and you need a separate input from the bodypix model I guess. Open for your ideas how to best achieve that.

**Comment by benbatya** [comment]
Hi @de-code, here's some thoughts:
Maybe we can build a simple data-flow API which can define nodes with zero or more inputs and one ndarray output.
Data would be pushed from upstream nodes to downstream nodes.
To make the data-flow simpler, each source node will be notified of the new frame and will produce a new output.
Then the downstream nodes will take the output from the upstream nodes and process them and produce new output.
Nodes will be added using BFS queue which adds a node once all of its inputs are ready.
Input/output compatibility is checked whenever a node is processed. This could also be done once lazily.
For simplicity, a valid connection is a output and input ndarray with matching dims on all axes. 
All of a node's inputs must be connected in order for it to be validated.

So for replace background of a movie:
1. the webcam node outputs a 640x480x3 ndarray and is marked as a source node
2. The video_player node outputs a 640x480x3 ndarray and is marked as a source node
2. the bodypix node input a 640x480x3 ndarray is connected to the webcam output and it outputs 2 640x480x1 ndarrays which are labelled as "all_mask" and "face_mask"
3. The erode node input is 640x480x1 and is connected to the bodypix.all output and outputs a 640x480x1 ndarray
4. dilate, blur and motion_blur are the same as erode
5. The composite node inputs are 640x480x3 background, 640x480x3 foreground and a 640x480x1 mask and its output is 640x480x3
5. The video_player output is connected to the composite bg input, the webcam output is connected to the composite's fg input and the motion_blur output is connected to the composite's mask
6. The window node input is connected to the composite's output and has a 0x0x0 output

webcam -> bodypix -> erode -> dilate -> blur -> motion_blur -> composite -> window
            \-------------------------------------------------------------------------/\        /\
video_player ---------------------------------------------------------------------------/
A more flexible connection system would be nice to allow for ANYxANYx1 style dim definitions and use dynamic dim checking & pass through during the lazy check.
Another approach would be to use gstreamer with the python API and convert bodypix to a gstreamer node.

What do you think?

**Comment by de-code** [comment]
Thank you for putting your thoughts down. I will need some time to read and understand it properly.
The current system is pull rather than push. It seemed easier to make things lazy. But I will read your proposal more carefully.

But just as you mentioned gstreamer. There is Google Coral's [project-bodypix](https://github.com/google-coral/project-bodypix) which is using gstreamer. But as far as I understand is only supporting Coral Edge TPU. It might be something to look for inspiration. I don't have any experience with the gstreamer API (only from vague recollections it required more system dependencies).

**Comment by benbatya** [comment]
Making it pull would be fine for small graphs.
If the graph gets big enough, then turning it into a efficient multi-process app will be more difficult.
Queuing and distributing large numbers of nodes calculations will be easier with a push system.
But maybe that's over-designing the system. 
And I have no idea how to efficiently pass ndarrays between multiple python processes.

**Comment by benbatya** [comment]
Hi @de-code I got inspired about your lazy pull approach so I adopted it for a more general graph. 
The graph is acyclic and dependent nodes must appear after their dependees.

Running the graph consists of recursively calling node.calculate() starting with the last node.
Normally the output of called node would be the default input of the calling node. 
But if a node needs more then one input or default input is not connected to default output, it can add that request to a map of output-requests. 
When a output matches an output-request, its added to the map before returning the default output.
This means that memory reallocation for default connections ("input: prev_node.output") is eliminated

Steps of Node.calculate():
1. Check if the node has any inputs.
2. if so, add non-default requests to the output-requests map and call the previous node in the list with the map
3. Gather and validate the inputs from the returned default value and output-requests map
4. Run the filter/source/sink code on the inputs to produce outputs
5. Store the output-request values into the map and return the default output

This way the nodes can be purely functional and lazily pulled.
Here's an example configuration:
```yml
nodes:
  - source: video_source
    # id: bg  # id is optional. type name is default for id. Since each id must be unique in the graph,
    # if two nodes of the same type are created, use id to identify them 
    # Source: https://www.pexels.com/video/carnival-rides-operating-in-an-amusement-park-3031943/
    input_path: "https://www.dropbox.com/s/oqftndbs29g8ekd/carnival-rides-operating-in-an-amusement-park-3031943-360p.mp4?dl=1"
    repeat: true
    preload: true
  - source: webcam
    device_path: "/dev/video0"
    fourcc: "MJPG"
  - filter: bodypix  # automatic connection from webcam.output to bodypix.input
    model_path: "https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/050/model-stride16.json"
    # model_path: "https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/model-stride16.json"
    internal_resolution: 0.5
    threshold: 0.5
  - filter: erode  
    # input: bodypix.output # bodypix default output is the all mask
    value: 20
  - filter: dilate  # automatic connection
    value: 19
  - filter: box_blur
    value: 10
  - filter: motion_blur
    frame_count: 3
    decay: 0
  - filter: composite
    # input: motion_blur.output   # NOTE: this isn't needed. It would be the default connection anyway
    input_fg: webcam.output
    input_bg: video_source.output
  - filter: auto_track      # crops input to crop_mask, adds a padding and then resizes back to the size of input array
    # input: composite.output # NOTE: not needed
    crop_input: bodypix.output_face # Alternative is a union node of bodypix.output_lface and bodypix.output_rface
    padding: 20
  - sink: v4l2_loopback
    device_path: "/dev/video4"
```
